version: "3"
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    #    ports:
    #      - 8082:80
    volumes:
      - $DOCKERHOME/:/srv
      - $DOCKERHOME/appdata/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.file-browser.entrypoints=http
      - traefik.http.routers.file-browser.rule=Host(`filebrowser.local.example.com`)
      - traefik.http.middlewares.file-browser-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.file-browser.middlewares=file-browser-https-redirect
      - traefik.http.routers.file-browser-secure.entrypoints=https
      - traefik.http.routers.file-browser-secure.rule=Host(`filebrowser.local.example.com`)
      - traefik.http.routers.file-browser-secure.tls=true
      - traefik.http.routers.file-browser-secure.service=file-browser
      - traefik.http.services.file-browser.loadbalancer.server.port=80
      - traefik.docker.network=proxy
networks:
  proxy:
    external: true
