services:
  twingate_connector:
    container_name: twingate
    restart: always
    image: twingate/connector:latest
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - TWINGATE_API_ENDPOINT=/connector.stock
      - TWINGATE_NETWORK=$TWINGATE_NETWORK
      - TWINGATE_ACCESS_TOKEN=$TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN=$TWINGATE_REFRESH_TOKEN
      - TWINGATE_LOG_LEVEL=3
    sysctls:
      net.ipv4.ping_group_range: 0 2147483647
    networks:
      - proxy
networks:
  proxy:
    external: true
