version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockage
    #    ports:
    #      - 5001:5001
    environment:
      DOCKGE_STACKS_DIR: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERHOME/appdata/dockge/data:/app/data
      - $DOCKERHOME/appdata:/opt/stacks
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.entrypoints=http
      - traefik.http.routers.dockge.rule=Host(`dockge.local.eaxmple.com`)
      - traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.dockge.middlewares=dockge-https-redirect
      - traefik.http.routers.dockge-secure.entrypoints=https
      - traefik.http.routers.dockge-secure.rule=Host(`dockge.local.example.com`)
      - traefik.http.routers.dockge-secure.tls=true
      - traefik.http.routers.dockge-secure.service=dockge
      - traefik.http.services.dockge.loadbalancer.server.port=5001
      - traefik.docker.network=proxy
networks:
  proxy:
    external: true
