version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      TZ: Europe/London
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_STOPPED: false
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: docker-live
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: $SMTP_EMAIL_FROM
      WATCHTOWER_NOTIFICATION_EMAIL_TO: $SMTP_EMAIL_TO
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: $SMTP_EMAIL_SERVER
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: $SMTP_EMAIL_SERVER_PORT
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: $SMTP_EMAIL_SERVER_USER
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: $SMTP_EMAIL_SERVER_PASSWORD
      WATCHTOWER_SCHEDULE: 00 30 03 * * SUN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - proxy
networks:
  proxy:
    external: true
