version: "3.1"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    #    ports:
    #      - 8902:8080
    volumes:
      - $DOCKERHOME/appdata/homer/assets:/www/assets
      - $DOCKERHOME/appdata/homer:/www/config.yml
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.entrypoints=https
      - traefik.http.routers.homer.rule=Host(`homer.local.example.com`)
      - traefik.http.middlewares.homer-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.homer.middlewares=homer-https-redirect
      - traefik.http.routers.homer-secure.entrypoints=https
      - traefik.http.routers.homer-secure.rule=Host(`homer.local.example.com`)
      - traefik.http.routers.homer-secure.tls=true
      - traefik.http.routers.homer-secure.service=homer
      - traefik.http.services.homer.loadbalancer.server.port=8080
      - traefik.docker.network=proxy
networks:
  proxy:
    external: true
