version: "3.1"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - $DOCKERHOME/appdata/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    #    ports:
    #      - 3001:3001
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=https
      - traefik.http.routers.uptime-kuma.rule=Host(`status.local.example.com`) || Host(`status.example.com`)
      - traefik.http.middlewares.uptime-kuma-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.uptime-kuma.middlewares=uptime-kuma-https-redirect
      - traefik.http.routers.uptime-kuma-secure.entrypoints=https
      - traefik.http.routers.uptime-kuma-secure.rule=Host(`status.local.example.com`) || Host(`status.example.com`)
      - traefik.http.routers.uptime-kuma-secure.tls=true
      - traefik.http.routers.uptime-kuma-secure.service=uptime-kuma
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.docker.network=proxy
networks:
  proxy:
    external: true
